name: flutter_painter
version: 1.0.1
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/omarhurani/flutter_painter
repository: https://github.com/omarhurani/flutter_painter
issue_tracker: https://github.com/omarhurani/flutter_painter/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  oktoast: ^3.3.1
  image: ^3.2.0
  event_bus: ^2.0.0


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
